import Head from 'next/head'
import { withLayout } from '@/layout/layout'
import Intro from '@/components/Intro';

function Home() {
  return (
    <>
        <Head>
            <title>Home - Based Movies</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div style={{color: '#FFFFFF'}}>
            <Intro />
        </div>
    </>
  )
}


export default withLayout(Home);